# Generated by Django 4.2.5 on 2023-09-16 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_friend_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_number', models.IntegerField()),
                ('page', models.IntegerField()),
                ('validity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=39)),
            ],
        ),
        migrations.DeleteModel(
            name='Me',
        ),
        migrations.AddField(
            model_name='passport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='first_app.person'),
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
            ],
            options={
                'ordering': ['id'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('first_app.friend',),
        ),
    ]
