# Generated by Django 4.2.5 on 2023-09-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
    ]
